package TryCatch.java;

public class Test2 {

	public static void main(String[] args) {

			    try {
			      int[] myNumbers = {1, 2, 3};
			      System.out.println(myNumbers[10]);
			    } 
			    catch (Exception v) {
			      System.out.println("Something went wrong.");
			    }
	}
}
			  

